defaults:
  - /model/modules/blocks@conv_block: conv_next_block
  - /model/modules/blocks@up_sampling_block: transposed_conv_upsample
  - /model/modules/blocks@lstm_block: conv_lstm_block
  - /model/modules/blocks@output_layer: output_layer

_target_: training.dlwp.model.modules.decoder.UNetDecoder
_recursive_: false
n_channels:
  - 256
  - 128
  - 64
n_layers:
  - 1
  - 2
  - 2
dilations:
  - 1
  - 1
  - 1
