# Analyses to perform
analyses:
  - acc
  - rmse
  - ssim
  - rmse_per_face
  - image_series_native

# Variables to evaluate
evaluate_variables_in_parallel: True
variables:
  - t2m0
  - z500

# Path where the results are written to
evaluation_directory: evaluation/outputs/hpx64_cos100_plat300

# Forecasts and overrides
forecasts:
  src_path: /home/disk/brume/karlbam
  
  models:
    HPX64 c360 plateau 300 epochs:  # Name of the model for plots and target directory determination
      forecast_path: dunet3/evaluation/forecasts/forecast_06-02-02_hpx64_u3p_c360_lr2e-4_plat_ep300_vNone.nc
      general_overrides:  # Applied to all analyses
        - paths.verification_ll=/home/rhodium/dlwp/data/HPX64/era5_1deg_3h_HPX64_1979-2018_
        - evaluator/remap_config=hpx64  # Use the hpx64 instead of the hpx32 remap config in the evaluator

    HPX64 c360 cosine 100 epochs:
      forecast_path: DELUSioN/evaluation/forecasts/forecast_06-02-02_hpx64_u3p_c360-180-90_ep100_vNone.nc
      general_overrides:
        - transfer_das=True  # Re-use the verification DataArrays generated by previous model
        - verbose=False
        - paths.verification_ll=/home/rhodium/dlwp/data/HPX64/era5_1deg_3h_HPX64_1979-2018_
        - evaluator/remap_config=hpx64
      analysis_overrides:  # Applied to a specific analysis only
        rmse_per_face:
          - analysis.skip=True  # Do not perform rmse_per_face analysis for this model/forecast

    HPX32 6var c90:
      forecast_path: DELUSioN/evaluation/forecasts/forecast_06-02-02_hpx_u3p_6var_c90-180-360_vNone.nc
      general_overrides:
        - verbose=False
      analysis_overrides:  # Applied to a specific analysis only
        acc:
          - analysis.on_latlon=True  # Default
        rmse:
          - analysis.on_latlon=False  # Perform analysis on native geometry (here HPX)

    CS64 gelu:
      forecast_path: DELUSioN/evaluation/forecasts/forecast_06-02-02_unet_gelu_ep300_vNone.nc
      general_overrides:
        - verbose=False
        - rescale_das=True  # Rescale the forecast (and verification if on native grid)
        - evaluator=cs  # Use the cubed sphere evaluator config
        - analysis.on_latlon=False  # Perform all analyses on native geometry (here CS)
        - paths.verification_ll=/home/disk/brume/karlbam/Data/DLWP/CS64/era5_1deg_3h_CS64S_1979-2018_
