_target_: training.dlwp.model.models.hpx_unet.Unet3plusDecoder
_recursive_: false
n_channels:
  - 256
  - 128
  - 64
convolutions_per_depth: 2
kernel_size: 3
dilations:
  - 4
  - 2
  - 1
pooling_type: 'torch.nn.MaxPool2d'
pooling: 2
upsampling_type: interpolate
upsampling: 2
activation:
  _target_: training.dlwp.model.layers.activations.CappedGELU
  cap_value: 10.