defaults:
  - encoder: hpx_unet3plus_encoder
  - decoder: hpx_unet3plus_decoder
  - loss: mse
  - optimizer: adam
  - scheduler: plateau

_target_: training.dlwp.model.models.HEALPixUnet
_recursive_: false
input_time_dim: ${data.input_time_dim}
output_time_dim: ${data.output_time_dim}
nside: ${data.nside}
batch_size: ${batch_size}

# Parameters automatically overridden in train code
# input_channels
# output_channels
# n_constants
# decoder_input_channels
input_channels: 6
output_channels: 6
n_constants: 2
decoder_input_channels: 1