name: Run unittests

on:
  push:
    branches:
      - dlesm

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: zephyr-1.0
        environment-file: environments/zephyr-1.0.yml
        auto-activate-base: false

    - name: Run tests
      run: |
        conda activate zephyr-1.0
        python -m unittest discover -p *_test.py
```   shell: bash -l {0}